### ISSUE TITLE
Lo que hablamos con Pablo

### ISSUE THREAD

**Issue by jnielavitzky** [kcortes95/itbar#1]
# Service Repository
Singleton que contenga a todos los service, asi podemos instanciar y manipular las variables internas de los services

# Session
Mover lo que esta como variables estaticas a la sesion

# Callbacks
Poner dos metodos

      - (void)success
      - (void)error

# Remote Exception
Matar excepciones en el middleware
Cambiar por Remote Error

**Comment by mgoffan** [comment]
@jnielavitzky fijate creo que ya hice todo

Tambien te cree la opcion de tener campos numericos  y el form de order. Create los form que necesites en FormBuilder
